<?php

namespace JagdishJP\SBIPay\Messages;

use Illuminate\Support\Str;
use Illuminate\Support\Facades\Config;
use JagdishJP\SBIPay\Traits\Encryption;

class Message {
	use Encryption;

	/**
	 * Transaction Id For Each Payment
	 *
	 */
	public $transactionId;

	/**
	 * Transaction Id generated by SBI on each transaction
	 *
	 */
	public $foreignId;

	/**
	 * Seller ID provided by SBI
	 */
	public $merchantKey;

	/**
	 * Account ID provided by SBI
	 */
	public $merchantId;

	/**
	 * Seller bank code used in the transaction
	 */
	public $aggregatorId;

	/**
	 * SBI used Verision
	 */
	public $version;

	/**
	 * Currency
	 */
	public $currency;

	/**
	 * Total amount to be paid
	 */
	public $amount;

	/**
	 * datetime of the transaction in YYYYMMDDHHmmSS format
	 */
	public $timestamp;

	/**
	 * datetime of the transaction generate from SBI in YYYYMMDDHH24MISS
	 */
	public $foreignTimestamp;

	/**
	 * Reference Number used to reference the transaction
	 */
	public $reference;

	/**
	 * The customer email address (optional)
	 */
	public $buyerEmail;

	/**
	 * The customer name
	 */
	public $buyerName;

	/**
	 * Buyer Account ID used for identify verification. (Optional)
	 */
	public $buyerAccountNumber;

	/**
	 * The customer id on the SBI side. (Only For B2B2) (Optional For B2C)
	 */
	public $buyerId;


	/**
	 * The selected bank ID by the customer
	 */
	public $targetBankId;

	/**
	 * The bank branch where the customer opened his/her account in. (Only For B2B2)
	 */
	public $targetBankBranch;

	/**
	 * The bank account number of the customer. (Only For B2B2)
	 */
	public $targetBankAccountNumber;

	/**
	 * Buyer representative (Maker) who initiate the transaction. (Only For B2B2)
	 */
	public $buyerMakerName;

	/**
	 * Buyer IBAN. (Only For B2B2)
	 */
	public $buyerIBAN;

	/**
	 * Product Description
	 */
	public $productDescription;

	/**
	 * Credit Card response status sent by SBI
	 */
	public $creditResponseNumber;
	public $creditResponseStatus;

	/**
	 * Debit Card response status sent by SBI
	 */
	public $debitResponseNumber;
	public $debitResponseStatus;

	/**
	 * Response checksum
	 */
	public $checkSum;

	/**
	 * Response array
	 */
	 public array $response;

	public function __construct() {
		$this->transactionId = Str::random(12);
		$this->aggregatorId = Config::get('sbi-pay.aggregator_id');
		$this->merchantId = Config::get('sbi-pay.merchant_id');
		$this->merchantKey = Config::get('sbi-pay.merchant_key');
		$this->currency = Config::get('sbi-pay.currency');
		$this->version = Config::get('sbi-pay.version');
	}
}
